version: "2.1"

services:

  client:
    image: postgres
    command: "yes"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
