version: "2.1"

# The api application needs to be provided with 2 environmental variables
# in order for it to run for development, and for it to run tests on an
# isolated testing database:
#   - DEV_DB_HOST
#   - TEST_DB_HOST

services:

  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      dev_postgres:
        condition: service_healthy
      test_postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=docker_dev

  dev_postgres:
    image: postgres:9.6.3-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      - POSTGRES_DB=users_with_secrets

  test_postgres:
    image: postgres:9.6.3-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      - POSTGRES_DB=users_with_secrets
