FROM node:8-alpine

RUN mkdir /app
WORKDIR /app

# TODO Build out the rest of this Dockerfile
# Currently it does not
#   - Install dependencies
#   - Install application code
#   - Make any ports exposed for outside access

CMD ["npm", "start"]
