version: "2.1"

# This `docker-compose.yml` needs completing.
#
# Specifically, the `api` service it defines is expecting two
# environmental variables that it has not yet been provided:
#
#   - `DEV_DB_HOST`
#   - `TEST_DB_HOST`
#
# Your task is to provide these 2 environmental variables
# to the `api` service, and, to give them values
# that will allow the containerized `api` service to connect
# to the `dev-db` and `test-db` services respectively.

services:

  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      dev_postgres:
        condition: service_healthy
      test_postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=docker_dev

  dev_db:
    image: postgres:9.6.3-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      - POSTGRES_DB=users_with_secrets

  test_db:
    image: postgres:9.6.3-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      - POSTGRES_DB=users_with_secrets
